### ISSUE TITLE
Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old

### ISSUE THREAD

**Issue by deepak-agendaboa** [benyap/firestore-backfire#266]
Getting the following error while exporting the data from Firestore collection

```
backfire 1:58:02 PM error   Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old.
    at callErrorFromStatus (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/client.js:351:73)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /usr/local/lib/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/client.js:334:34)
    at ServiceClientImpl.<anonymous> (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /usr/local/lib/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:225:29
    at /usr/local/lib/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /usr/local/lib/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
    at makeRequest (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/retry-request/index.js:141:28)
    at retryRequest (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/retry-request/index.js:109:5)
    at StreamProxy.setStream (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streaming.js:121:37)
    at StreamingApiCaller.call (/usr/local/lib/node_modules/@google-cloud/firestore/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:54:16) {
  code: 9,
  details: 'The requested snapshot version is too old.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
```

How to solve this issue?

I have ~17,00,000 documents in a collection. The error is after exporting ~12,00,000 documents.

**Comment by benyap** [comment]
Hey @deepak-agendaboa. I'm not sure that I have an easy solution for this one.

The error `FAILED_PRECONDITION: The requested snapshot version is too old.` can happen when you are trying to read a lot of data from Firestore at once.

In most places in the code for Firestore Backfire, data reads are chunked to avoid this error. I can't say I've tested this with 17,000,000 documents, so I haven't come across this issue before personally.

One place you could try to address this would be to use the `downloadChunkSize` option - see [here](https://github.com/benyap/firestore-backfire#options) for the documentation.

**What `downloadChunkSize` controls**

Every `exploreInterval` (which is 10ms by default), a request is made to look for paths to export. Any matching paths that are found are collected in a buffer.

Every `downloadInterval` (which is 1000ms by default), Firestore Backfire will attempt to download documents in that buffer using the [getAll()](https://cloud.google.com/nodejs/docs/reference/firestore/latest/firestore/firestore#_google_cloud_firestore_Firestore_getAll_member_1_) method. By default, it will try to download **everything** in the buffer (as `downloadChunkSize` is not defined by default). However, if `downloadChunkSize` is defined, it will only download up to a maximum of `downloadChunkSize` documents at once.

This may help as if for whatever reason, a large number of documents are present in the buffer, it will prevent all of them from being downloaded at once. But also be aware - if this limit is set too low, you may also be throttling the performance of the export.
